### ISSUE TITLE
typo in customise dogears

### ISSUE THREAD

**Issue by jack99999** [alphapapa/dogears.el#10]
i get this as a customisation option:

Show Value Dogears Sidebar Alist 
   Alist passed to ‘display-buffer-in-side-window’, which see.

i think that should probably be 'which side', not 'which see'?

**Comment by alphapapa** [comment]
No, "which see" is an English idiom which corresponds to the Latin abbreviation "q.v."  It's commonly used in Emacs documentation.  You can search emacs-devel for more information.
