### ISSUE TITLE
Let the bookmark system know it's called by dogears

### ISSUE THREAD

**Issue by novoid** [alphapapa/dogears.el#13]
Hi,

I do have a "funny" request. As you can read [on reddit](https://www.reddit.com/r/emacs/comments/siphk3/comment/hzfwwln/), I forgot that I added dogears to my config. As I added ID property support for my bookmark system using my own `my-id-get-or-generate` function to generate human-readable ID properties on bookmarking, I noticed that IDs were generated without my interaction.

oantolin reminded me of `debug-on-entry` which revealed the forgotten nugget of dogears.

Therefore: **is there a sane way of letting my custom bookmark function that it is called by dogears** in order to omit generating IDs and using the default bookmark concept?

So far, I setup dogears for testing purposes and I'm not sure if it brings much benefit to my current situation. So if the answer is "yes but this requires ugly hacks", we can agree on closing this issue.

Thanks for you thoughts on that!

**Comment by alphapapa** [comment]
Hi Karl,

I tend to forget that I have `dogears` turned on too, even though I wrote it.  :)  I, too, am not sure how much benefit it offers, but it seemed like something that ought to exist in Emacs; maybe if I remember to use it more often, it will help me more...

Anyway, I guess a simple solution would be to bind a variable to non-nil while Dogears is making a bookmark, and then your ID-generator function could check that variable's value.  That could be added to Dogears itself, or you could use `:around` function advice to do it entirely in your config.  I'd probably prefer that you do the latter, unless this becomes a common need for other users.  :)

**Comment by novoid** [comment]
Thanks for the idea. I'll find a way to fix this in my config as it seems to be an issue that is only related to my specific setup.
