### ISSUE TITLE
Possibly bugs in `dogears-go` and `dogears-forward`?

### ISSUE THREAD

**Issue by all9n** [alphapapa/dogears.el#15]
First of all, thanks for the package!

I see 2 places that might be bugs. (Disclaimer: relatively new to Emacs and don't understand how bookmarks work.)

- In `dogears-forward`, it seems `(nth -1000 '(a b c))` returns `a`, so `dogears-index` could go negative?
- In `dogears-go`, `(bookmark-jump place)` returns `nil` after jumping (at least for me) so the `or` below is kind of pointless. https://github.com/alphapapa/dogears.el/blob/c05b69e504a538c9e00fbb0ea86934fafe191d0c/dogears.el#L234-L236

**Comment by alphapapa** [comment]
Thanks.  I'll fix this when I get a chance.

**Comment by gitrj95** [comment]
i put up a pr for the former: https://github.com/alphapapa/dogears.el/pull/19

**Comment by alphapapa** [comment]
@all9n This should be fixed by the changes in v0.2-pre.  Thanks.
