### ISSUE TITLE
Document in the README how to remove the dogear indicator in the gutter

### ISSUE THREAD

**Issue by philc** [alphapapa/dogears.el#17]
I began seeing these markers after installing dogears. Is this using the emacs marker system? If so, mentioning this and pointing the user how to customize/disable their display would be helpful. I'd prefer not to see them.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/8598/195532363-8bd85167-a1e8-4be4-8776-6e7463660410.png">

**Comment by alphapapa** [comment]
Dogears uses the Emacs bookmark system internally.  Those fringe markers are a controversial feature added to the Emacs bookmark system in Emacs 28.  They can be disabled with a customization option, the name of which I don't recall.
