### ISSUE TITLE
dogears-functions can break interactive commands

### ISSUE THREAD

**Issue by protesilaos** [alphapapa/dogears.el#7]
Hello Adam and thanks for sharing this package!

Here is a bug I found on Emacs 28.  With `emacs -Q` I evaluate this:

```elisp
(require 'dogears "/path/to/dogears.el")

(setq dogears-functions '(find-file switch-to-buffer))

(dogears-mode 1)
```

Then when I try to use either of the `dogears-functions`, I get these messages:

```
apply: Wrong number of arguments: #<subr find-file>, 0

apply: Wrong number of arguments: #<subr switch-to-buffer>, 0
```

**Comment by alphapapa** [comment]
Hi Prot,

Thanks for reporting this, but I can't understand why this would happen.  Those functions are advised to call `dogears-remember` afterward, and that function has `(&rest _ignore)` as its argument list, so it doesn't care how many arguments it receives.

I see that those functions are shown as subrs, which probably means you're using native-comp.  Are you using the latest version of Emacs 28.0.50?  If so, you might need to report this as an Emacs bug.

**Comment by protesilaos** [comment]
> Thanks for reporting this, but I can't understand why this would happen.  Those functions are advised to call `dogears-remember` afterward, and that function has `(&rest _ignore)` as its argument list, so it doesn't care how many arguments it receives.

You are welcome! As I am not too familiar with the advice system, the `(&rest _ignore)` basically accepts it as-is without asking for other arguments?

> I see that those functions are shown as subrs, which probably means you're using native-comp.  Are you using the latest version of Emacs 28.0.50?  If so, you might need to report this as an Emacs bug.

Yes, I am on native-comp.  Though I will rebuild on top of master today and then report the bug.  This recipe on emacs -Q gives the error:

    (defun test-advice (&rest _ignore)
      (interactive)
      (message "test"))

    (advice-add #'switch-to-buffer :after #'test-advice)

**Comment by alphapapa** [comment]
> As I am not too familiar with the advice system, the `(&rest _ignore)` basically accepts it as-is without asking for other arguments?

The advice system has no knowledge of what arguments advised functions or advice functions expect.  See the documentation for `add-function`.

> Yes, I am on native-comp. Though I will rebuild on top of master today and then report the bug. This recipe on emacs -Q gives the error:

I'm unable to reproduce that error on Emacs 26.3 or my fairly recent build of Emacs 28.0.50.

**Comment by alphapapa** [comment]
Please disregard the message I just wrote and deleted.  This seems to be relate to using interactive functions as advice functions, not a bug in Emacs, although I don't understand why it's happening.

**Comment by alphapapa** [comment]
The answer appears to be here, in the manual entry for `add-function`:

```
     If FUNCTION is not interactive, then the combined function will
     inherit the interactive spec, if any, of the original function.
     Else, the combined function will be interactive and will use the
     interactive spec of FUNCTION.  One exception: if the interactive
     spec of FUNCTION is a function (rather than an expression or a
     string), then the interactive spec of the combined function will be
     a call to that function with as sole argument the interactive spec
     of the original function.  To interpret the spec received as
     argument, use ‘advice-eval-interactive-spec’.

     Note: The interactive spec of FUNCTION will apply to the combined
     function and should hence obey the calling convention of the
     combined function rather than that of FUNCTION.  In many cases, it
     makes no difference since they are identical, but it does matter
     for ‘:around’, ‘:filter-args’, and ‘:filter-return’, where FUNCTION
     receives different arguments than the original function stored in
     PLACE.
```
I didn't know that the advice function effectively changes the interactive spec of the advised function.  I'm not sure of the best way to fix this, given that the list of advised functions is configurable by the user.

**Comment by alphapapa** [comment]
It looks like this will work, so I guess this needs to be done for each advised function:
```el
(defun test-advice (&rest _ignore)
  (message "test"))

(advice-add #'switch-to-buffer :after
	    `(lambda (&rest _ignore)
	       ,(interactive-form 'switch-to-buffer)
	       (message "test")))
```

**Comment by protesilaos** [comment]
Oh, interesting find! Your new code works fine on my end.

**Comment by protesilaos** [comment]
That was quick.  Thank you!

**Comment by alphapapa** [comment]
That seems to work, both when enabling and disabling the mode with `switch-to-buffer` in `dogears-functions`.  Thanks for reporting.  (We appear to be writing simultaneously.  :)
