### ISSUE TITLE
Function helm-make-source called during package-initialize before helm is loaded

### ISSUE THREAD

**Issue by marcel-becker** [alphapapa/dogears.el#9]
Hi, 
I installed dogears using elpa/quelpa. 
It installs fine and runs fine after installation.  
When I re-start emacs, the call to (package-initialize) early on on my init file causes the error (void-function helm-make-source) since helm has not been loaded yet.  I am running 
Is there a way to load helm before dogears is loaded?

I compile emacs from source and I am using the latest version from git on MacOs  BigSur 11.6:
Emacs git commit:  
commit 338af9213d6cb47da9c1835d20d8db27b915b3d1 (HEAD -> master, origin/master, origin/HEAD)
Author: Lars Ingebrigtsen <larsi@gnus.org>
Date:   Fri Sep 17 18:37:51 2021 +0200

Stack trace for the error: 

Debugger entered--Lisp error: (void-function helm-make-source)
  (helm-make-source "Dogears" 'helm-source-sync :candidates #'(lambda nil (let* ((--cl-var-- dogears-list) (place nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq place (car --cl-var--)) (setq --cl-var-- (cons (cons ... place) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--))) :action (list (cons "Go to place" #'dogears-go)))
  (defvar helm-dogears-source (helm-make-source "Dogears" 'helm-source-sync :candidates #'(lambda nil (let* ((--cl-var-- dogears-list) (place nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq place (car --cl-var--)) (setq --cl-var-- (cons ... --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--))) :action (list (cons "Go to place" #'dogears-go))))
  eval-buffer(#<buffer  *load*-271998> nil "/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." nil t)  ; Reading at buffer position 2249
  load-with-code-conversion("/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." "/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." nil t)
  load("/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." nil t)
  package--activate-autoloads-and-load-path(#s(package-desc :name dogears :version (20210902 2214) :summary "Never lose your place again" :reqs ((emacs (26 3)) (map (2 1))) :kind nil :archive nil :dir "/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." :extras ((:url . "https://github.com/alphapapa/dogears.el") (:keywords "convenience") (:maintainer "Adam Porter" . "adam@alphapapa.net") (:authors ("Adam Porter" . "adam@alphapapa.net"))) :signed nil))
  package--load-files-for-activation(#s(package-desc :name dogears :version (20210902 2214) :summary "Never lose your place again" :reqs ((emacs (26 3)) (map (2 1))) :kind nil :archive nil :dir "/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." :extras ((:url . "https://github.com/alphapapa/dogears.el") (:keywords "convenience") (:maintainer "Adam Porter" . "adam@alphapapa.net") (:authors ("Adam Porter" . "adam@alphapapa.net"))) :signed nil) nil)
  package-activate-1(#s(package-desc :name dogears :version (20210902 2214) :summary "Never lose your place again" :reqs ((emacs (26 3)) (map (2 1))) :kind nil :archive nil :dir "/Users/marcelbecker/Dropbox/.emacs.d/elpa/dogears-..." :extras ((:url . "https://github.com/alphapapa/dogears.el") (:keywords "convenience") (:maintainer "Adam Porter" . "adam@alphapapa.net") (:authors ("Adam Porter" . "adam@alphapapa.net"))) :signed nil) nil deps)
  package-activate(dogears)
  package--activate-all()
  package-activate-all()
  package-initialize()

**Comment by alphapapa** [comment]
I think the problem is that you installed with Quelpa, and the recipe in the readme doesn't exclude `helm-dogears.el`.  If you reinstall the package from MELPA, that file should not be installed.
